### ISSUE TITLE
Error while loading shared libraries: libOpenImageIO.so.1.3 observed on my Ubuntu16.04+AMD card plugged in

### ISSUE THREAD

**Issue by saipoorna** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#71]
Tried running App on Ubuntu16.04, and I get below error. But the same worked fine on Ubuntu14.04

### _../Bin/Release/x64/App64: error while loading shared libraries: libOpenImageIO.so.1.3: cannot open shared object file: No such file or directory_

The error still occurs even after installing the below dependencies.
sudo apt-get install libopenimageio-dev libglew-dev freeglut3-dev

Could you please let us know if I am missing something here?

\Thanks.

**Comment by citrix123** [comment]
Hi Saipoorna,
  I am using 16.04 and it works like charm. 
May be you can check the presence of library, if that is on Present or not. 
try: ldd ../Bin/Release/x64/App64

Here is my output: 
```
root@local:~/Documents/RadeonRays_SDK/App# ldd ../Bin/Release/x64/App64  | grep -i libopenimage
        libOpenImageIO.so.1.6 => /usr/lib/libOpenImageIO.so.1.6 (0x00007fc813809000)

```
Thanks,
Rahul

**Comment by yozhijk** [comment]
Hi @saipoorna ,

Any luck checking @citrix123 suggestion?

**Comment by saipoorna** [comment]
Hi,
I've built it in Ubuntu14.04  and is working fine on the same machine. When I try to run this App in Ubuntu16.04, it is throwing the said error.
I see libOpenImageIO.so.1.6 @ /usr/lib. However, the APP is looking for libOpenImageIO.so.1.**3** (1.3 version). Probably building it again in Ubuntu16.04 should solve the problem i believe.

\Thanks,

**Comment by yozhijk** [comment]
Hi @saipoorna ,

Ubuntu 14.04 and 16.04 come with different version of libOpenImageIO.so and these versions are not binary compatible (symbolic link does not solve the problem). So the version built on 14.04 is not going to work on 16.04, you have to rebuild it on 16.04.
